#!/bin/busybox sh

echo 'AFTER MOUNT STUFF'
busybox mount

# okay busybox pivot_root . . from / doesn't work EBUSY says we're on the current root mount
# busybox pivot_root . .

# but this works
cd /mnt/bundle/rootfs
busybox pivot_root . .
echo $?

# strace -f -o strace.out crun run --bundle /mnt/bundle containerid-1234
# busybox cat strace.out
