#!/bin/busybox sh

export PATH=/bin

# otherwise we get a kernel panic and the vmm process hangs
trap "busybox poweroff -f" EXIT

# crun needs /proc/self/exe for stuff, cgroup_root for containers, and devtmpfs for mounting our sqfs
busybox mount -t proc none /proc
busybox mount -t cgroup2 none /sys/fs/cgroup
busybox mount -t devtmpfs none /dev
#busybox mount -t squashfs -o loop /dev/vda /run/bundle/rootfs
busybox mount -t squashfs -o loop /dev/pmem0 /run/bundle/rootfs

#exit
busybox sleep 10

echo 'about to echo to pmem'
busybox date -Ins > /dev/pmem1
echo 'done to echo to pmem'

# busybox unshare --mount /bin/busybox sh -c 'busybox mount --rbind / /abc && cd /abc && busybox mount --move . / && busybox chroot . /bin/init3'
# busybox unshare --mount /bin/init2

# --- INPUT ---
# HOST takes files, creates cpio and sends them through socket
# cpio -o < file-list | socat - UNIX-LISTEN:/tmp/ch.sock_123
# OR
# sstream u/tmp/ch.sock_123 1 cpio < file-list  # run cpio with stdout replaced by socket unix at that path
#
# GUEST reads from socket 123 and sends stdout to cpio
# socat - VSOCK-LISTEN:123 | cpio -i -D /input
# or
# sstream v123 0 cpio -i -D /input  # run cpio with stdin replaced by socket

# --- OUTPUT ---
# HOST listens on vsock and captures output
# socat - UNIX-LISTEN:/tmp/ch.sock_124 > output.cpio
# or
# sstream u/tmp/ch.sock_124 1 > output.cpio
#
# GUEST sends on vsock
# echo -e 'file1\nfile2' | cpio -o | socat - VSOCK-CONNECT:124
# or
# echo -e 'file1\nfile2' | sstream v124 1 cpio -o

vsockhello v123 0 /bin/busybox cat > /input/_stdin

echo '---------from guest--------------'
echo '-------- stdin -----------'
echo '--------------------------'
busybox cat /input/_stdin
echo '--------------------------'

# pivot_rootfs /abc /bin/init3
pivot_rootfs /abc \
  /bin/crun run --bundle /run/bundle containerid-1234 \
  < /input/_stdin \
  > _stdout \
  2> _stderr

echo '---------from guest--------------'
echo '-------- stdout -----------'
busybox cat _stdout
echo '---------------------------'

echo '-------- stderr -----------'
busybox cat _stderr
echo '---------------------------'

#crun run --parent-rootfs /abc --bundle /run/bundle containerid-1234

echo -e '_stdout\n_stderr' | vsockhello v124 1 busybox cpio -H newc -o
