#!/bin/busybox sh

busybox mount --rbind / /abc

echo '---------------------mount --rbind / /abc -------------------------------'
busybox cat /proc/self/mountinfo
echo '-------------------------------------------------------------------------'

cd /abc
busybox mount --move . /

echo '----------------cd /abc && mount --move . / -----------------------------'
busybox cat /proc/self/mountinfo
echo '-------------------------------------------------------------------------'

exec busybox chroot . /bin/init3
