#!/bin/busybox sh

export PATH=/bin

# otherwise we get a kernel panic and the vmm process hangs
trap "busybox poweroff -f" EXIT

# crun needs /proc/self/exe for stuff, cgroup_root for containers, and devtmpfs for mounting our sqfs
busybox mount -t proc none /proc
busybox mount -t cgroup2 none /sys/fs/cgroup
busybox mount -t devtmpfs none /dev

echo 'hi'

busybox mount
busybox cat /proc/self/mountinfo
# busybox ls -l /
# busybox ls -l /dev
# busybox ls -l /proc

# passing in --disk...id=foo doesn't show up on blkid though

busybox blkid
busybox mount -t squashfs -o loop /dev/vda /run/bundle/rootfs

# crun spec --file /run/bundle/config.json
# busybox mv /config.json /run/bundle/config.json
busybox ls -l /run/bundle/

# busybox cat /run/bundle/config.json
# busybox ls -l /proc/self/
# echo 'my cgroup is'
# busybox cat /proc/self/cgroup

# busybox cat /proc/cgroups

# errors b/c new_mnt is MNT_LOCKED whether we are in / or /abc
# busybox mkdir /abc
# cd /abc
# busybox pwd
# busybox pivot_root . .

echo 'running init2'
echo '---------------------mountinfo before -----------------------------------'
busybox cat /proc/self/mountinfo
echo '-------------------------------------------------------------------------'
busybox unshare --mount /bin/init2

# busybox unshare --mount /bin/busybox sh -c 'busybox mount --rbind / /abc && cd /abc && busybox mount --move . / && busybox chroot . /bin/init3'

echo '---------------------mountinfo init1 after ---------------------------'
busybox cat /proc/self/mountinfo
echo '----------------------------------------------------------------------'

# strace -o strace.out -f /bin/init3
# busybox cat strace.out
