[package]
name = "peerofs"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
bytes = "1.10.1"
memmap2 = "0.9.5"
rustix = { version = "1.0.5", features = ["fs"] }
zerocopy = { version = "0.8.24", features = ["derive", "std"] }

[lib]
path = "src/lib.rs"

[[bin]]
name = "erofs-dump"
path = "src/dump.rs"

[lints]
workspace = true

[dev-dependencies]
tempfile = "3.19.1"
