[package]
name = "peimage"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
oci-spec = "0.7.0"
peinit = { version = "0.1.0", path = "../peinit" }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
flate2 = {version = "1.1.1", features = ["zlib-ng"] }
tar = "0.4.44"

[lib]
path = "src/lib.rs"

[[bin]]
name = "squash"
path = "src/squashbin.rs"

[[bin]]
name = "squash-podman"
path = "src/squashpodman.rs"

[[bin]]
name = "squash-oci"
path = "src/squashoci.rs"

[lints]
workspace = true
