[package]
name = "peserver"
version = "0.1.0"
edition = "2021"
default-run = "peserver"


[[bin]]
name = "testclient"
path = "src/testclient.rs"

[dependencies]
byteorder = "1.5.0"
clap = "4.5.20"
nix = { version = "0.29.0", features = ["socket"] }
peimage = { version = "0.1.0", path = "../peimage" }
peinit = { version = "0.1.0", path = "../peinit" }
perunner = { version = "0.1.0", path = "../perunner" }
serde = { version = "1.0.214", features = ["serde_derive"] }
serde_json = "1.0.132"
tempfile = "3.14.0"
