[package]
name = "peserver"
version = "0.1.0"
edition = "2021"
default-run = "peserver"


[[bin]]
name = "testclient"
path = "src/testclient.rs"

[dependencies]
async-trait = "0.1.83"
bincode = "1.3.3"
byteorder = "1.5.0"
bytes = "1.8.0"
clap = "4.5.21"
http = "1.1.0"
peimage = { version = "0.1.0", path = "../peimage" }
peinit = { version = "0.1.0", path = "../peinit" }
perunner = { version = "0.1.0", path = "../perunner", features = ["asynk"] }
pingora = "0.4.0"
pingora-timeout = "0.4.0"
serde = { version = "1.0.214", features = ["serde_derive"] }
serde_json = "1.0.132"
tempfile = "3.14.0"
tokio = { version = "1.41.1", features = ["io-util"] }
