[package]
name = "peserver"
version = "0.1.0"
edition = "2021"
default-run = "peserver"


[[bin]]
name = "testclient"
path = "src/testclient.rs"

[dependencies]
atoi_simd = "0.16.0"
byteorder = "1.5.0"
clap = "4.5.20"
http = "1.1.0"
httparse = "1.9.5"
mio = { version = "1.0.2", features = ["net"] }
nix = { version = "0.29.0", features = ["time"] }
peimage = { version = "0.1.0", path = "../peimage" }
peinit = { version = "0.1.0", path = "../peinit" }
perunner = { version = "0.1.0", path = "../perunner" }
serde = { version = "1.0.214", features = ["serde_derive"] }
serde_json = "1.0.132"
tempfile = "3.13.0"
tokio = { version = "1.41.0", features = ["io-util", "macros", "net", "rt", "time"] }
