[package]
name = "perunner"
version = "0.1.0"
edition = "2021"

[dependencies]
api_client = { version = "0.1.0", path = "../../cloud-hypervisor/api_client" }
pearchive = { version = "0.1.0", path = "../pearchive" }
peinit = { version = "0.1.0", path = "../peinit" }
libc = "0.2.158"
rand = "0.8.5"
wait-timeout = "0.2.0"
bincode = "1.3.3"
serde = "1.0.210"
oci-spec = "0.7.0"
serde_json = "1.0.128"
base16ct = {version = "0.2.0", features = ["alloc"] }
sha2 = "0.10.8"
escape-bytes = "0.1.1"
byteorder = "1.5.0"
